# Generated by Django 5.2 on 2025-04-10 06:06

import django.db.models.deletion
import django_countries.fields
import multiselectfield.db.fields
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=1, verbose_name='gender')),
                ('birth_date', models.DateField(verbose_name='birth date')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='ucountry')),
                ('profile_picture', models.ImageField(upload_to='media', verbose_name='profile picture')),
                ('hobbies', multiselectfield.db.fields.MultiSelectField(choices=[('S', 'sports'), ('M', 'music'), ('T', 'travel')], max_length=5, verbose_name='hobbies')),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='mobile number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
